name: Docker Image CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          #docker login --username=${{ secrets.ALIYUN_REGISTRY_USER }} --password=${{ secrets.ALIYUN_REGISTRY_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker login --username=${{ secrets.ALIYUN_REGISTRY_USER }} --password=${{ secrets.ALIYUN_REGISTRY_PASSWORD }} crpi-001becofmssbtwfb.cn-chengdu.personal.cr.aliyuncs.com
          #cd xxl-job-admin
          cd docker_images
          # 使用Dockerfile构建镜像
          #docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/kdyzm/xxl-job-admin:2.4.1
          docker build . --file Dockerfile --tag crpi-001becofmssbtwfb.cn-chengdu.personal.cr.aliyuncs.com/fgtest/docker_images:1.0
          # 推送镜像到镜像仓库
          #docker push registry.cn-hangzhou.aliyuncs.com/kdyzm/xxl-job-admin:2.4.1
          docker push crpi-001becofmssbtwfb.cn-chengdu.personal.cr.aliyuncs.com/fgtest/docker_images:1.0
